apiVersion: apps/v1
kind: Deployment
metadata:
  name: vinay-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: vinay-container
        image: nginx:latest
        ports:
        - containerPort: 8080
