apiVersion: apps/v1
kind: Deployment
metadata:
  name: vinay-dep-cip
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vinay-app-cip
  template:
    metadata:
      labels:
        app: vinay-app-cip
    spec:
      containers:
      - name: vinay-container
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vinay-app-cip
  labels:
    app: vinay-app-cip
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: vinay-app-cip