apiVersion: apps/v1
kind: Deployment
metadata:
  name: vinay-dep-np
spec:
  selector:
    matchLabels:
      app: vinay-app-np
  replicas: 3
  template:
    metadata:
      labels:
        app: vinay-app-np
    spec:
      containers:
      - name: vinay-nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vinay-app-np
  labels: 
    app: vinay-app-np
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: vinay-app-np